spring.datasource.url=jdbc:postgresql://localhost:5432/YourDatabase
spring.datasource.username=
spring.datasource.password=Yourpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

api.security.token.secret=YoursecretToken