spring.datasource.url=jdbc:postgresql://localhost:5432/yourbanco
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

api.security.token.secret=yourtoken